package homeworks.homework13.io;

public enum Command {
  TEST_DATA_CREATE,
  ENTIRE_LIST_SHOW,
  FAMILY_MEMBERS_MORE_THAN_SHOW,
  FAMILY_MEMBERS_LESS_THAN_SHOW,
  FAMILY_MEMBERS_EQUALS_COUNT,
  FAMILY_CREATE,
  FAMILY_INDEX_DELETE,
  FAMILY_INDEX_EDIT,
  ALL_CHILDREN_ABOVE_AGE_REMOVE,
  SAVE_DATA,
  LOAD_DATA,
  HELP,
  EXIT

}
